language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - pip install -r requirements.txt
  - pip install codecov
install:
  - python setup.py install
script:
  - pytest test/

